spring:
     mail:
      host: smtp.gmail.com
      port: 587
      username: skyminlee93@gmail.com
      password: avotccbhjnzbxszy
      properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true