spring:
     mail:
      host: smtp.gmail.com
      port: 587
      username: skyminlee9@gmail.com
      password: ecphrhjgyvrlgecz
      properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true